import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp,writeFile,rm} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {createHash} from 'node:crypto';
import {loadResearchAssets} from '../apps/preview/research-assets.mjs';
import {previewServer} from '../apps/preview/server.mjs';
const hash=b=>createHash('sha256').update(b).digest('hex');
async function fixture(t){const dir=await mkdtemp(join(tmpdir(),'dkb-interior-'));t.after(()=>rm(dir,{recursive:true,force:true}));const binary=Buffer.alloc(84);[0,0,0,1,0,0,0,1,0,0,0,1,0,0,1,0,0,1].forEach((x,i)=>binary.writeFloatLE(x,i*4));[0,1,2].forEach((x,i)=>binary.writeUInt32LE(x,72+i*4));const manifest={format:'dkb-research-mesh-v1',id:'kang-2024-pulp-v1',license:'CC-BY-4.0',reviewStatus:'pending-human-academic-and-release-review',clinicalMeasurement:false,registrationToWholeMouth:false,models:['tooth','pulp','pdl'].map(id=>({id,file:id+'.bin',vertices:3,triangles:1,sha256:hash(binary)}))};for(const m of manifest.models)await writeFile(join(dir,m.file),binary);await writeFile(join(dir,'ATTRIBUTION.txt'),'Synthetic attribution fixture, not an anatomical asset.');const save=()=>writeFile(join(dir,'manifest.json'),JSON.stringify(manifest));await save();return{dir,manifest,save,binary};}
async function server(t,options){const s=previewServer(options);await new Promise(r=>s.listen(0,'127.0.0.1',r));t.after(()=>new Promise(r=>{s.close(r);s.closeAllConnections();}));return`http://127.0.0.1:${s.address().port}`;}
test('research data is absent by default, while the page offers a clear unavailable state',async t=>{const url=await server(t);assert.equal((await fetch(url+'/tooth-interior')).status,200);assert.equal((await fetch(url+'/research/pulp/tooth.bin')).status,404);assert.equal((await(await fetch(url+'/health')).json()).interiorResearchEnabled,false);});
test('only explicit validated research resources are served; archives and path traversal stay blocked',async t=>{const f=await fixture(t);const assets=await loadResearchAssets(f.dir);const url=await server(t,{researchAssets:assets});await writeFile(join(f.dir,'tooth.bin'),'changed after startup');assert.equal(hash(Buffer.from(await(await fetch(url+'/research/pulp/tooth.bin')).arrayBuffer())),f.manifest.models[0].sha256);assert.equal((await(await fetch(url+'/health')).json()).interiorResearchEnabled,true);for(const file of ['manifest.json','tooth.bin','pulp.bin','pdl.bin','ATTRIBUTION.txt'])assert.equal((await fetch(url+'/research/pulp/'+file)).status,200);for(const file of ['models.zip','46.stp','../manifest.json','%2e%2e%2f.env'])assert.equal((await fetch(url+'/research/pulp/'+file)).status,404);});
test('unknown license, public-approval claim and arbitrary model filename are rejected',async t=>{for(const change of [m=>m.license='unknown',m=>m.reviewStatus='approved',m=>m.registrationToWholeMouth=true,m=>m.models[0].file='../secret']){const f=await fixture(t);change(f.manifest);await f.save();await assert.rejects(loadResearchAssets(f.dir));}});
test('tampered data, invalid vertex values and out-of-bounds triangles fail before serving',async t=>{for(const type of ['hash','vertex','index']){const f=await fixture(t);if(type==='hash')f.binary[0]=123;if(type==='vertex')f.binary.writeFloatLE(NaN,0);if(type==='index')f.binary.writeUInt32LE(99,72);await writeFile(join(f.dir,'tooth.bin'),f.binary);if(type!=='hash'){f.manifest.models[0].sha256=hash(f.binary);await f.save();}await assert.rejects(loadResearchAssets(f.dir));}});
