import {writeFile,mkdir} from 'node:fs/promises';
import assert from 'node:assert/strict';
const [endpoint,target,output,mode='readonly']=process.argv.slice(2);
if(!endpoint||!target||!output)throw Error('Usage: CDP_URL PAGE_URL OUTPUT [intake]');
if(mode==='intake'&&new URL(target).hostname!=='127.0.0.1')throw Error('Synthetic intake tests require isolated localhost');
await mkdir(output,{recursive:true});const pages=await(await fetch(endpoint+'/json/list')).json();const page=pages.find(p=>p.type==='page');const ws=new WebSocket(page.webSocketDebuggerUrl);await new Promise(r=>ws.onopen=r);let seq=0;const jobs=new Map(),errors=[],passed=[];
ws.onmessage=e=>{const m=JSON.parse(e.data);if(m.id){const p=jobs.get(m.id);jobs.delete(m.id);m.error?p.reject(m.error):p.resolve(m.result);}if(m.method==='Runtime.exceptionThrown')errors.push(m.params.exceptionDetails.text);};
const call=(method,params={})=>new Promise((resolve,reject)=>{const id=++seq;jobs.set(id,{resolve,reject});ws.send(JSON.stringify({id,method,params}));});
const ev=async expression=>{const r=await call('Runtime.evaluate',{expression,returnByValue:true,awaitPromise:true});if(r.exceptionDetails)throw Error(JSON.stringify(r.exceptionDetails));return r.result.value;};const sleep=ms=>new Promise(r=>setTimeout(r,ms));const wait=async expr=>{for(let i=0;i<300;i++){if(await ev(expr))return;await sleep(150);}throw Error('Timeout '+expr);};
const click=async selector=>{await ev(`document.querySelector(${JSON.stringify(selector)}).click()`);await sleep(180);};const snapshot=()=>ev('__interior.snapshot()');const capture=()=>ev('__interior.captureView()');const slider=async(id,value)=>{await ev(`(()=>{const el=document.getElementById('${id}');el.value=${value};el.dispatchEvent(new Event('input'));})()`);await sleep(150);};const shot=async name=>writeFile(output+'/'+name+'.png',Buffer.from((await call('Page.captureScreenshot')).data,'base64'));
try{
 await call('Runtime.enable');await call('Page.enable');await call('Emulation.setDeviceMetricsOverride',{width:1600,height:1000,deviceScaleFactor:1,mobile:false});await call('Page.navigate',{url:target});await wait('window.__interior?.snapshot().frames>0');await sleep(500);
 let s=await snapshot();assert.equal(s.source,'kang-2024-pulp-v1');assert.equal(s.pdl,false);assert.equal(s.reviewStatus,'pending-human-academic-and-release-review');assert.ok(s.layers.every(x=>x.closed));passed.push('source assembly loads; review pending; schematic layer off');await shot('interior-overview');
 await click('[data-step=surface]');s=await snapshot();assert.equal(s.opacity,1);assert.equal(s.cut,false);await shot('outer-surface');passed.push('outer source surface preset');
 await click('[data-step=pulp]');s=await snapshot();assert.equal(s.tooth,false);assert.equal(s.pulp,true);passed.push('isolated cavity preset');
 await click('[data-step=section]');s=await snapshot();assert.equal(s.cut,true);assert.equal(s.layers.filter(x=>x.cap).length,2);await shot('section-oblique');passed.push('closed meshes have stencil section fills');
 for(const axis of ['x','z','y']){await click(`[data-axis=${axis}]`);await slider('cut-position',35);await click('#face-cut');assert.equal((await snapshot()).axis,axis);await shot('section-'+axis);}
 passed.push('three source-axis cuts and face-cut views');
 await slider('tooth-opacity',30);await shot('section-transparent');assert.equal((await snapshot()).layers[0].cap,true);await slider('tooth-opacity',100);passed.push('section fills survive opacity changes');
 await click('#flip');assert.equal((await snapshot()).flipped,true);await click('#center-cut');assert.equal((await snapshot()).position,50);await click('#cut');assert.ok((await snapshot()).layers.every(x=>!x.cap));passed.push('flip, center and cut-off restore');
 await click('[data-step=relation]');await slider('tooth-opacity',0);assert.equal((await snapshot()).layers[0].visible,false);await slider('tooth-opacity',70);assert.equal((await snapshot()).layers[0].opacity,.7);passed.push('opacity endpoints and restoration');
 await click('#pdl-visible');await click('#cut');await wait('__interior.snapshot().geometries===6');const warm=(await snapshot()).geometries;for(let i=0;i<4;i++){await click('#cut');await click('#cut');}assert.equal((await snapshot()).geometries,warm);passed.push('cut toggles reuse GPU geometries');
 await click('[data-step=relation]');await click('#fit');const distance=x=>Math.hypot(...x.camera.map((v,i)=>v-x.target[i]));const before=distance(await snapshot());await click('#zoom-in');assert.ok(distance(await snapshot())<before);await click('#zoom-out');passed.push('zoom buttons have correct direction');
 await ev('document.querySelector("canvas").focus()');const keyboardBefore=(await snapshot()).camera;await call('Input.dispatchKeyEvent',{type:'keyDown',key:'ArrowLeft',code:'ArrowLeft'});await call('Input.dispatchKeyEvent',{type:'keyUp',key:'ArrowLeft',code:'ArrowLeft'});await sleep(300);assert.notDeepEqual((await snapshot()).camera,keyboardBefore);passed.push('focused canvas supports keyboard rotation');
 await call('Emulation.setDeviceMetricsOverride',{width:390,height:844,deviceScaleFactor:1,mobile:true});await call('Emulation.setTouchEmulationEnabled',{enabled:true,maxTouchPoints:2});await click('#fit');await sleep(400);assert.ok(await ev('document.documentElement.scrollWidth<=innerWidth'));await shot('mobile');
 const point=await ev('(()=>{const r=document.querySelector("#interior-canvas").getBoundingClientRect();return{x:r.left+r.width/2,y:r.top+r.height*.55}})()');const beforeTouch=(await snapshot()).camera;await call('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:point.x-30,y:point.y,id:1},{x:point.x+30,y:point.y,id:2}]});await call('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:point.x-65,y:point.y,id:1},{x:point.x+65,y:point.y,id:2}]});await call('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});await sleep(300);assert.notDeepEqual((await snapshot()).camera,beforeTouch);passed.push('mobile fits and touch pinch works');
 await call('Emulation.setDeviceMetricsOverride',{width:1600,height:1000,deviceScaleFactor:1,mobile:false});await call('Emulation.setTouchEmulationEnabled',{enabled:false});await ev('scrollTo(0,0)');await click('#sources');assert.ok(await ev('document.querySelector("#source-dialog").open'));assert.ok(await ev('document.querySelector("#source-dialog").textContent.includes("0,15")'));await click('#close-sources');passed.push('source, license and discrepancy explanation accessible');
 await click('[data-step=section]');await click('[data-axis=z]');await slider('cut-position',45);await click('#face-cut');await sleep(400);const original=await capture();await click('[data-step=surface]');await ev(`__interior.restoreView(${JSON.stringify(original)})`);let restored=await capture();assert.deepEqual(restored.state,original.state);for(let i=0;i<3;i++)assert.ok(Math.abs(restored.camera[i]-original.camera[i])<.001);passed.push('versioned cut/camera snapshot round trip');
 if(mode==='intake'){
  await wait('!document.querySelector("#contribute").disabled');await click('#contribute');await ev(`document.querySelector('[name=description]').value='Synthetic interior view replay verification only';document.querySelector('[name=consent]').checked=true;document.querySelector('#contribution-form').requestSubmit()`);await wait('document.querySelector("#contribution-dialog a[href*=contributions]")');const link=await ev('document.querySelector("#contribution-dialog a[href*=contributions]").href');await call('Page.navigate',{url:link});await wait('document.querySelector("#replay-view")');const replay=await ev('document.querySelector("#replay-view").href');assert.equal(new URL(replay).pathname,'/tooth-interior');await call('Page.navigate',{url:replay});await wait('document.querySelector(".contribution-toast")');restored=await capture();assert.deepEqual(restored.state,original.state);assert.deepEqual(restored.assets,original.assets);for(let i=0;i<3;i++)assert.ok(Math.abs(restored.camera[i]-original.camera[i])<.001);passed.push('private contribution restores research viewer and exact source/cut state');
 }
 const stale=structuredClone(await capture());stale.assets.pulp='0'.repeat(64);assert.equal(await ev(`(()=>{try{__interior.restoreView(${JSON.stringify(stale)});return false;}catch{return true;}})()`),true);passed.push('stale source hash refuses replay');
 await click('[data-step=relation]');await click('#fit');await sleep(800);const idle=(await snapshot()).frames;await sleep(500);assert.equal((await snapshot()).frames,idle);passed.push('renderer stops drawing when idle');assert.deepEqual(errors,[]);passed.push('no runtime exceptions');await writeFile(output+'/result.json',JSON.stringify({passed,errors,final:await snapshot()},null,2));console.log(JSON.stringify({passed,errors}));
}finally{ws.close();}
