import {mkdir,writeFile} from 'node:fs/promises';
import assert from 'node:assert/strict';
const [,,endpoint='http://127.0.0.1:9222',target='http://192.168.1.192:3057/',output='/tmp/dkb-anatomy-proof']=process.argv;
await mkdir(output,{recursive:true});
const pages=await(await fetch(endpoint+'/json/list')).json();
const page=pages.find(p=>p.type==='page'&&p.url.startsWith(new URL(target).origin));
if(!page)throw Error('Open the target preview in the local debugging Chrome first');
const ws=new WebSocket(page.webSocketDebuggerUrl);await new Promise(r=>ws.addEventListener('open',r,{once:true}));
let id=0;const pending=new Map(),errors=[],passed=[];
ws.addEventListener('message',e=>{const m=JSON.parse(e.data);if(m.id){const p=pending.get(m.id);pending.delete(m.id);m.error?p.reject(m.error):p.resolve(m.result);}if(m.method==='Runtime.exceptionThrown')errors.push(m.params);});
const call=(method,params={})=>new Promise((resolve,reject)=>{const n=++id;pending.set(n,{resolve,reject});ws.send(JSON.stringify({id:n,method,params}));});
const ev=async expression=>{const r=await call('Runtime.evaluate',{expression,returnByValue:true,awaitPromise:true});if(r.exceptionDetails)throw Error(JSON.stringify(r.exceptionDetails));return r.result.value;};
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
const wait=async expr=>{for(let i=0;i<150;i++){if(await ev(expr))return;await sleep(100);}throw Error('Timeout '+expr);};
const click=async sel=>{await ev(`document.querySelector(${JSON.stringify(sel)}).click()`);await sleep(200);};
const snap=()=>ev('__anatomy.snapshot()');
const shot=async name=>writeFile(output+'/'+name+'.png',Buffer.from((await call('Page.captureScreenshot')).data,'base64'));
await call('Runtime.enable');await call('Page.enable');await call('Emulation.setDeviceMetricsOverride',{width:1600,height:1000,deviceScaleFactor:1,mobile:false});
await call('Page.navigate',{url:target});await wait('window.__anatomy?.snapshot().frames>0');await sleep(1500);
assert.equal((await snap()).visibleTeeth,28);assert.equal((await snap()).pulpAvailable,false);passed.push('28 source teeth; no invented pulp');await shot('mouth-final');
await click('[data-view="front"]');const point=await ev('__anatomy.project(11)');
await call('Input.dispatchMouseEvent',{type:'mousePressed',x:point.x,y:point.y,button:'left',clickCount:1});await call('Input.dispatchMouseEvent',{type:'mouseReleased',x:point.x,y:point.y,button:'left',clickCount:1});
assert.equal((await snap()).selected,11);passed.push('raycast source tooth selection');
await click('[data-jaw="lower"]');assert.equal((await snap()).visibleTeeth,14);assert.equal((await snap()).selected,41);passed.push('jaw filter and matching FDI');
await click('[data-fdi="36"]');await click('#focus');assert.equal((await snap()).mode,'tooth');assert.equal((await snap()).selected,36);await sleep(400);await shot('tooth36');passed.push('isolation with source roots');
const gpu=[];for(let i=0;i<3;i++){await click('#home');await click('#focus');gpu.push((await snap()).geometryMemory);}assert.equal(new Set(gpu).size,1);passed.push('shared geometry survives focus cycles');
const before=(await snap()).camera;await click('#zoom-in');await sleep(300);assert.ok(Math.hypot(...(await snap()).camera)<Math.hypot(...before));passed.push('zoom direction');
await click('#home');await click('[data-jaw="both"]');await click('#roots');assert.equal((await snap()).roots,true);await shot('roots');await click('#bones');assert.equal((await snap()).bones,true);await shot('bones');passed.push('source roots and jaw bones');
await click('#sources');assert.equal(await ev('document.querySelector("dialog").open'),true);assert.equal(await ev('document.querySelectorAll("dialog [download]").length'),2);await click('#close-sources');passed.push('attribution and downloadable derivative');
await click('#bones');await click('#roots');
await call('Emulation.setDeviceMetricsOverride',{width:390,height:844,deviceScaleFactor:1,mobile:true});await call('Emulation.setTouchEmulationEnabled',{enabled:true,maxTouchPoints:2});await sleep(500);assert.ok(await ev('document.documentElement.scrollWidth<=innerWidth'));await shot('mobile');passed.push('mobile layout without overflow');
const r=await ev('(()=>{const r=document.querySelector("#canvas").getBoundingClientRect();return{x:r.left+r.width/2,y:r.top+r.height/2}})()');
const startCamera=(await snap()).camera;
await call('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:r.x-25,y:r.y,id:1},{x:r.x+25,y:r.y,id:2}]});
await call('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:r.x-60,y:r.y,id:1},{x:r.x+60,y:r.y,id:2}]});
await call('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});await sleep(300);assert.notDeepEqual((await snap()).camera,startCamera);passed.push('touch pinch');
assert.equal(errors.length,0);passed.push('no runtime exceptions');
await writeFile(output+'/browser-result.json',JSON.stringify({passed,gpu,errors,final:await snap()},null,2));console.log(JSON.stringify({passed,gpu,errors}));ws.close();
